PlannerApp/config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:create, :new, :show, :index]
  resource :session, only: [:create, :destroy, :new]
  resources :goals, except: [:new, :index, :show]
end

PlannerApp/app/models/goal.rb
class Goal < ActiveRecord::Base
  validates :body, :user_id, presence: true
  validates :private, inclusion: { in: [true, false] }

  belongs_to :user
end

PlannerApp/app/models/goal_comment.rb
class GoalComment < ActiveRecord::Base
  validates :goal_id, :body, presence: true

  belongs_to :goal
  belongs_to :user
end

PlannerApp/app/models/user.rb
class User < ActiveRecord::Base
  validates :username, :password_digest, :session_token, presence: true
  validates :password, length: { minimum: 6, allow_nil: true }

  attr_reader :password

  before_validation :ensure_session_token

  has_many :goals

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)
    return nil unless user && user.is_password?(password)
    user
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def reset_session_token!
    self.session_token = User.generate_session_token
    self.save!
    self.session_token
  end

  def self.generate_session_token
    SecureRandom.urlsafe_base64
  end

  private
  def ensure_session_token
    self.session_token ||= User.generate_session_token
  end
end

PlannerApp/app/models/user_comment.rb
class UserComment < ActiveRecord::Base
  validates :user_id, :body, presence: true

  belongs_to :user
  belongs_to :comment
end

PlannerApp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user, :signed_in?

  def current_user
    @current_user ||= User.find_by_session_token(session[:session_token])
  end

  def sign_in(user)
    #user.session_token = user.reset_session_token!
    session[:session_token] = user.reset_session_token!
  end

  def signed_in?
    !!current_user
  end

  def require_signed_in
    redirect_to session_new_url unless signed_in?
  end

  def log_out
    current_user.reset_session_token!
    session[:session_token] = nil
  end

end

PlannerApp/app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  before_action :user_owns_goal, only: [:edit, :update, :destroy]

  def create
    @goal = Goal.new(goal_params)
    @goal.user_id = current_user.id
    @goal.save
    flash.now[:errors] = @goal.errors.full_messages
    redirect_to user_url(current_user)
  end

  def edit
  end

  def update
    if @goal.update(goal_params)
      redirect_to user_url(@goal.user_id)
    else
      flash.now[:errors] = @goal.errors.full_messages
      render :edit
    end
  end

  def destroy
    @goal.destroy
    redirect_to user_url(@goal.user_id)
  end

  private
  def goal_params
    params.require(:goal).permit(:body, :private)
  end

  def user_owns_goal
    @goal = current_user.goals.find(params[:id])
    unless @goal
      flash[:errors] = ["This goal is not for you!"]
      redirect_to user_url(current_user)
    end
  end
end

PlannerApp/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by_credentials(
      params[:user][:username],
      params[:user][:password]
    )

    if user
      sign_in(user)
      redirect_to user_url(user)
    else
      flash.now[:errors] = "Invalid username or password"
      render :new
    end
  end

  def destroy
    log_out
    redirect_to new_session_url
  end
end

PlannerApp/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end
  
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      sign_in(@user)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private
  def user_params
    params.require(:user).permit(:username, :password)
  end
end

PlannerApp/app/helpers/application_helper.rb
module ApplicationHelper
end

PlannerApp/app/helpers/goals_helper.rb
module GoalsHelper
end

PlannerApp/app/helpers/sessions_helper.rb
module SessionsHelper
end

PlannerApp/app/helpers/users_helper.rb
module UsersHelper
end

PlannerApp/app/views/goals/edit.html.erb
<h1>Edit Goal!</h1>

<form action="<%= goal_url(@goal) %>" method="post">
  <input type="hidden" name="_method" value="patch">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <label>Goal
    <input type="text" name="goal[body]" value="">
  </label>
  <label>Private
    <input type="radio" name="goal[private]" value="true">
  </label>
  <label>Public
    <input type="radio" name="goal[private]" value="false">
  </label>
  <br>
  <input type="submit" value="Edit Goal!">

</form>

PlannerApp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PlannerApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% if current_user %>
    <%= current_user.username %>
    <%= button_to "Log Out", session_url, method: :delete %>
  <% else %>
    <%= link_to "Sign In", new_session_url %>
    <%= link_to "Sign Up", new_user_url %>
  <% end %>

<%= yield %>

</body>
</html>

PlannerApp/app/views/users/index.html.erb
<h1>All Users</h1>
<br>
<ul>
  <% @users.each do |user| %>
    <li>
      <%= link_to user.username, user_url(user) %> has <%= user.goals.count %> goals
    </li>
  <% end %>
</ul>

PlannerApp/app/views/users/new.html.erb
<h1>Sign Up</h1>
<form action="<%= users_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <label>Username
    <input type="text" name="user[username]" value="">
  </label>
  <label>Password
    <input type="password" name="user[password]" value="">
  </label>
  <input type="submit" value="Sign Up">

</form>

PlannerApp/app/views/users/show.html.erb
<h2><%= @user.username %> Goals</h2>
<ul>
<% @user.goals.each do |goal| %>
 <% if @user.id == current_user.id %>
    <%= goal.body %>
    <%= button_to "Update Goal!", edit_goal_url(goal), method: :get %>
    <%= button_to "Destroy Goal!", goal_url(goal), method: :delete %>
    <h5 style="font-family: arial padding: 0px">
      is this goal complete?
    </h5>  <p><%= goal.completion_status %></p>
  <% elsif goal.private == false  %>
    <%= goal.body %>
    <h5 style="font-family: arial padding: 0px">
      is this goal complete?
    </h5>  <p><%= goal.completion_status %></p>
  <% end %>


<% end %>
</ul>

<% if @user.id == current_user.id %>
  <form action="<%= goals_url %>" method="post">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <label>Goal
      <input type="text" name="goal[body]" value="">
    </label>
    <label>Private
      <input type="radio" name="goal[private]" value="true">
    </label>
    <label>Public
      <input type="radio" name="goal[private]" value="false">
    </label>
    <br>
    <input type="submit" value="Create Goal!">

  </form>
  <br>
<% end %>

<%= link_to "All Users", users_url %>